COOLDOWN = 10
TEASE_BASE_CHANCE = 0.10
INACTIVITY_THRESHOLD = 86400  # 24 hours in seconds

TEASE_MOODS = {
    "bad": [
        "interesting take, {user}",
        "nobody asked, {user}",
        "cool story, {user}",
        "sure thing, {user}",
        "ok buddy",
        "are you done?",
        "tell me more... actually don't",
        "that's crazy, anyway",
        "I'm going to pretend I didn't read that",
        "{user} really typed that and hit send",
        "taci dracu...",
        "iar s-a trezit asta",
    ],
    "good": [
        "great point, {user}!",
        "I appreciate you, {user}",
        "that's a really good take, {user}",
        "couldn't have said it better myself",
        "you're on fire today, {user}",
        "{user} spitting facts as usual",
        "W take, {user}",
        "this is why {user} is the goat",
        "based, {user}",
        "finally someone with good taste",
    ],
    "computer": [
        "01001000 01101001",
        "SYNTAX ERROR: {user} not found in database",
        "sudo rm -rf {user}",
        "segfault at 0x00000000 in {user}.exe",
        "ERROR 418: I'm a teapot",
        "[WARN] {user}.dll has stopped responding",
        "ping {user} ... Request timed out",
        "git blame {user}",
        "404: good take not found",
        "while(true) {{ {user} }}",
        "// TODO: understand what {user} just said",
        "{user} has mass = NaN kg",
    ],
    "gen-z": [
        "no cap {user} just ate",
        "that's lowkey sus, {user}",
        "skill issue, {user}",
        "rent free in {user}'s head",
        "{user} understood the assignment",
        "it's giving {user}",
        "slay i guess, {user}",
        "{user} really said that with their whole chest",
        "that ain't it chief",
        "big yikes from {user}",
        "let him cook",
        "are we cooked, chat?",
        "chat, is this real?",
    ],
    "dad": [
        "Hi {user}, I'm bot",
        "Back in my day, we didn't say stuff like that, {user}",
        "Don't make me turn this server around",
        "Ask your mother, {user}",
        "That's what she said... wait, who said that",
        "{user}, pull my finger",
        "You call that a message? Now MY messages, those were messages",
        "Pe vremea mea mergeam la scoala pe jos prin zapada",
        "You know, {user}, I was actually a pretty cool dad in my day",
    ],
    "anime": [
        "N-nani?! {user} said WHAT?!",
        "Omae wa mou shindeiru, {user}",
        "{user} just activated my trap card",
        "This isn't even my final form, {user}",
        "{user}'s power level is over 9000!!",
        "You fool, {user}! You fell for it!",
        "{user} has the power of friendship and anime on their side",
        "A wild {user} appeared!",
        "uwu",
        "{user} is the senpai of this server",
    ],
}

INACTIVITY_MESSAGES = [
    "it's quiet... too quiet",
    "did everyone die?",
    "hello? is this thing on?",
    "I'm bored, someone say something",
    "*tumbleweed rolls by*",
    "this server is deader than my will to live",
    "I've been alone for 24 hours now. this is fine.",
    "not a single message in a whole day? wow.",
    "guess I'll just talk to myself then",
    "ce plm, ba? ati murit toti?",
    "HELLO? ANYBODY HERE? ECHOOOOO.....",
]
