"""Stable persistence API grouped internally by data domain."""

from db.analytics import (
    get_analytics_summary,
    record_analytics_activity,
    refresh_analytics_command_catalog,
)
from db.bot_data import (
    _invalidate_responses_cache,
    add_joke,
    add_reminder,
    add_response,
    clear_guild_joke_config,
    delete_joke,
    delete_reminder,
    get_all_guild_activity,
    get_all_guild_joke_configs,
    get_all_jokes,
    get_all_reminders,
    get_all_responses,
    get_due_reminders,
    get_guild_joke_config,
    get_joke_by_id,
    get_llm_feedback_summary,
    get_llm_response_feedback,
    get_random_response,
    get_setting,
    get_top_keywords,
    get_top_keywords_by_user,
    get_unsent_joke_for_guild,
    is_guild_inactivity_enabled,
    log_keyword_usage,
    mark_guild_joke_sent,
    remove_response,
    reset_all_guild_joke_sent,
    reset_guild_joke_sent,
    set_guild_activity,
    set_guild_inactivity_enabled,
    set_guild_joke_config,
    set_guild_joke_last_sent,
    set_llm_response_rating,
    set_setting,
    track_llm_response,
    update_joke,
)
from db.connection import _connect
from db.constants import LLM_MEMORY_ENTRY_KINDS
from db.flights import (
    add_flight_price_history,
    add_flight_tracker,
    delete_flight_api_credentials,
    delete_flight_tracker,
    get_all_flight_trackers,
    get_flight_api_credentials,
    get_flight_price_history,
    get_flight_tracker,
    get_user_flight_trackers,
    set_flight_api_credentials,
    update_flight_tracker_result,
)
from db.memory import (
    add_llm_memory_observation,
    add_llm_memory_transcript,
    add_manual_llm_memory_entry,
    apply_llm_memory_delta,
    begin_llm_memory_cycle,
    clear_llm_memory_progress,
    complete_llm_memory_cycle_if_empty,
    delete_all_llm_user_memory,
    delete_llm_memory_channel_observations,
    delete_llm_memory_entries_by_text,
    delete_llm_memory_observations,
    delete_llm_user_memory,
    get_enabled_llm_memory_channels,
    get_llm_memory_channel_observations,
    get_llm_memory_entries,
    get_llm_memory_observation_channels,
    get_llm_memory_observations,
    get_llm_memory_preference,
    get_llm_memory_progress,
    get_llm_memory_transcript,
    get_llm_user_memory,
    is_llm_memory_channel_enabled,
    purge_guild_llm_user_memories,
    set_llm_memory_channel_enabled,
    set_llm_memory_preference,
    set_llm_user_memory,
)
from db.schema import init_db
from db.wishlist import (
    add_price_history,
    add_scraped_item,
    clean_old_price_history,
    delete_scraped_item,
    get_all_scraped_items,
    get_exchange_rate,
    get_price_history,
    get_scraped_item,
    get_user_scraped_items,
    get_user_scraped_items_for_refresh,
    get_user_scraped_items_with_settings,
    set_exchange_rate,
    set_scraped_item_restock_only,
    set_scraped_item_target,
    update_item_alert_state,
    update_scraped_item_check_status,
    update_scraped_item_status,
    update_scraped_item_target_state,
)

